window.onerror=m=>{const e=document.getElementById('err');e.style.display='block';e.textContent='Game error: '+m};
(()=>{'use strict';
const c=document.getElementById('c'),g=c.getContext('2d'),D=Math.min(devicePixelRatio||1,2),TW=64,TH=32,W=32,H=32;
let cam={x:innerWidth/2,y:-120,z:.82},drag=0,moved=0,last,sel='road',nid=1,ng=1,nc=1,nw=1,t0=performance.now(),toastTimer=0,selectedFlag=null;
const T={road:{n:'Road',i:'🛤️',co:{stone:1}},flag:{n:'Flag',i:'🚩',co:{wood:1}},wood:{n:'Woodcutter',i:'🪓',co:{wood:6,stone:2}},mill:{n:'Sawmill',i:'🪚',co:{wood:8,stone:3},mk:'planks',cy:5},quarry:{n:'Quarry',i:'⛏️',co:{wood:5},mk:'stone',cy:5},farm:{n:'Farm',i:'🌾',co:{wood:7,stone:2},mk:'food',cy:6},house:{n:'House',i:'🏠',co:{wood:10,planks:5,stone:4}},store:{n:'Storage',i:'📦',co:{wood:10,planks:6,stone:6}},tower:{n:'Tower',i:'🏰',co:{planks:8,stone:14}}};
let s={inv:{wood:100,logs:0,planks:24,stone:70,food:30},b:[],goods:[],carriers:[],workers:[],trees:[],delivered:0};
function resize(){c.width=innerWidth*D;c.height=innerHeight*D;c.style.width=innerWidth+'px';c.style.height=innerHeight+'px'}addEventListener('resize',resize);resize();
function iso(a,b){return{x:cam.x+(a-b)*TW*.5*cam.z,y:cam.y+(a+b)*TH*.5*cam.z}}
function uniso(a,b){let q=(a-cam.x)/cam.z,r=(b-cam.y)/cam.z;return{x:Math.floor(r/TH+q/TW),y:Math.floor(r/TH-q/TW)}}
function diamond(a,b,f,st){let p=iso(a,b),w=TW*.5*cam.z,h=TH*.5*cam.z;g.beginPath();g.moveTo(p.x,p.y);g.lineTo(p.x+w,p.y+h);g.lineTo(p.x,p.y+h*2);g.lineTo(p.x-w,p.y+h);g.closePath();g.fillStyle=f;g.fill();g.strokeStyle=st;g.lineWidth=.6;g.stroke()}
function at(a,b){return s.b.find(v=>v.x===a&&v.y===b)}
function roadish(a,b){let q=at(a,b);return q&&(q.type==='road'||q.type==='flag')}
function nbrs(a,b){return [[1,0],[-1,0],[0,1],[0,-1]].filter(([dx,dy])=>roadish(a+dx,b+dy)).map(([dx,dy])=>({x:a+dx,y:b+dy}))}
function afford(co){return Object.entries(co||{}).every(([k,v])=>(s.inv[k]||0)>=v)}
function flagFor(o){return s.b.find(f=>f.type==='flag'&&Math.abs(f.x-o.x)+Math.abs(f.y-o.y)===1)||null}
function toast(m){let e=document.getElementById('toast');e.textContent=m;e.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.classList.remove('show'),1300)}
function key(x,y){return x+','+y}
function path(a,b){if(!a||!b||!roadish(a.x,a.y)||!roadish(b.x,b.y))return[];let q=[[a.x,a.y]],h=0,seen=new Set([key(a.x,a.y)]),prev=new Map();while(h<q.length){let [x,y]=q[h++];if(x===b.x&&y===b.y){let out=[],k=key(x,y);while(k){let [px,py]=k.split(',').map(Number);out.push({x:px,y:py});k=prev.get(k)}return out.reverse()}for(let n of nbrs(x,y)){let k=key(n.x,n.y);if(!seen.has(k)){seen.add(k);prev.set(k,key(x,y));q.push([n.x,n.y])}}}return[]}
function connectedFlag(f){return !!f&&nbrs(f.x,f.y).length>0}
function initTrees(){s.trees=[];for(let y=2;y<H-2;y++)for(let x=2;x<W-2;x++){let n=Math.sin(x*.71+y*.43)+Math.sin(x*.19-y*.83);if(n>.72&&!roadish(x,y))s.trees.push({id:'t'+x+'-'+y,x,y,alive:true,reserved:null})}}
function add(type,a,b,free=0){if(a<0||b<0||a>=W||b>=H)return 0;let old=at(a,b);if(type==='flag'&&old&&old.type==='road'){if(!free&&!afford(T.flag.co)){toast('Not enough wood');return 0}if(!free)s.inv.wood--;old.type='flag';old.input={logs:0};selectedFlag=old.id;toast('Road converted to logistics flag');ensureCarriers();ui();return 1}if(old){if(old.type==='flag'){selectedFlag=old.id;ui();toast('Flag selected');return 1}toast('Tile occupied');return 0}if(type==='flag'&&!free&&nbrs(a,b).length===0){toast('Flags must connect to a road');return 0}if(!free&&!afford(T[type].co)){toast('Not enough resources');return 0}if(!free)Object.entries(T[type].co||{}).forEach(([k,v])=>s.inv[k]-=v);let o={id:nid++,type,x:a,y:b,t:0,input:{logs:0}};s.b.push(o);if(type==='flag'){selectedFlag=o.id;ensureCarriers()}if(type==='wood')s.workers.push({id:nw++,owner:o.id,x:a+.1,y:b+.1,state:'seek',target:null,chop:0,carry:false,speed:1.15});ui();return 1}
function destinations(kind,srcFlag){let types=kind==='logs'?['mill','store']:['store'],out=[];for(let type of types){for(let b of s.b.filter(v=>v.type===type)){let f=flagFor(b);if(!f)continue;let r=path(srcFlag,f);if(r.length)out.push({b,f,r,dist:r.length})}if(out.length)break}out.sort((a,b)=>a.dist-b.dist);return out}
function routeFlags(route,fromFlag,toFlag){let ids=[];for(let p of route){let f=at(p.x,p.y);if(f&&f.type==='flag'&&f.id!==fromFlag.id&&f.id!==toFlag.id)ids.push(f.id)}ids.push(toFlag.id);return ids}
function routeToFlag(from,to){let r=path(from,to);return r.length?r:[]}
function spawn(kind,src){let sf=flagFor(src);if(!sf)return;let options=destinations(kind,sf),d=options[0]||null;let hops=d?routeFlags(d.r,sf,d.f):[];s.goods.push({id:ng++,kind,x:sf.x,y:sf.y,src:src.id,currentFlag:sf.id,dst:d?d.b.id:null,toFlag:d?d.f.id:null,hops,carrier:null,blocked:!d})}
function refreshGood(item){if(item.carrier)return;let cf=s.b.find(b=>b.id===item.currentFlag);if(!cf)return;let dst=item.dst&&s.b.find(b=>b.id===item.dst),df=dst&&flagFor(dst);if(dst&&df){let r=path(cf,df);if(r.length){item.toFlag=df.id;item.hops=routeFlags(r,cf,df);item.blocked=false;return}}let opts=destinations(item.kind,cf),d=opts[0]||null;if(d){item.dst=d.b.id;item.toFlag=d.f.id;item.hops=routeFlags(d.r,cf,d.f);item.blocked=false}else item.blocked=true}
function ensureCarriers(){let fs=s.b.filter(b=>b.type==='flag'&&connectedFlag(b));let target=Math.min(5,Math.max(2,Math.ceil(fs.length/2)));while(s.carriers.length<target&&fs.length){let f=fs[s.carriers.length%fs.length];s.carriers.push({id:nc++,x:f.x,y:f.y,state:'idle',good:null,path:[],step:0,carry:null,speed:1.45})}}
function assign(){for(let item of s.goods)refreshGood(item);for(let c of s.carriers){if(c.state!=='idle')continue;let start={x:Math.round(c.x),y:Math.round(c.y)},pick=null,pickPath=[];for(let item of s.goods.filter(v=>!v.carrier&&!v.blocked)){let cf=s.b.find(b=>b.id===item.currentFlag),p=path(start,cf);if(p.length){pick=item;pickPath=p;break}}if(!pick)continue;pick.carrier=c.id;c.good=pick.id;c.path=pickPath;c.step=0;c.state='pickup'}}
function moveEntity(e,dt){if(e.step>=e.path.length)return 1;let t=e.path[e.step],dx=t.x-e.x,dy=t.y-e.y,d=Math.hypot(dx,dy);if(d<.04){e.x=t.x;e.y=t.y;e.step++;return e.step>=e.path.length}let m=Math.min(d,e.speed*dt);e.x+=dx/d*m;e.y+=dy/d*m;return 0}
function updateCarriers(dt){assign();for(let c of s.carriers){if(c.state==='idle')continue;let item=s.goods.find(v=>v.id===c.good);if(!item){c.state='idle';c.good=null;continue}if(c.carry){item.x=c.x;item.y=c.y}if(!moveEntity(c,dt))continue;if(c.state==='pickup'){let cf=s.b.find(b=>b.id===item.currentFlag),nextId=item.hops[0],nf=s.b.find(b=>b.id===nextId);let hop=routeToFlag(cf,nf);if(!hop.length){item.blocked=true;item.carrier=null;c.state='idle';c.good=null;continue}c.carry=item.kind;c.path=hop;c.step=0;c.state='drop'}else{let reached=item.hops.shift();item.currentFlag=reached;let f=s.b.find(b=>b.id===reached);item.x=f.x;item.y=f.y;item.carrier=null;c.carry=null;c.good=null;c.state='idle';c.path=[];if(reached===item.toFlag){let d=s.b.find(b=>b.id===item.dst);if(d&&d.type==='mill'&&item.kind==='logs')d.input.logs++;else if(d)s.inv[item.kind]=(s.inv[item.kind]||0)+1;s.goods=s.goods.filter(v=>v.id!==item.id);s.delivered++}else refreshGood(item)}}}
function nearestTree(worker,owner){let trees=s.trees.filter(t=>t.alive&&!t.reserved);trees.sort((a,b)=>(Math.abs(a.x-owner.x)+Math.abs(a.y-owner.y))-(Math.abs(b.x-owner.x)+Math.abs(b.y-owner.y)));return trees.find(t=>Math.abs(t.x-owner.x)+Math.abs(t.y-owner.y)<=8)||null}
function walkDirect(w,tx,ty,dt){let dx=tx-w.x,dy=ty-w.y,d=Math.hypot(dx,dy);if(d<.06){w.x=tx;w.y=ty;return true}let m=Math.min(d,w.speed*dt);w.x+=dx/d*m;w.y+=dy/d*m;return false}
function updateWorkers(dt){for(let w of s.workers){let o=s.b.find(b=>b.id===w.owner);if(!o)continue;if(w.state==='seek'){let t=nearestTree(w,o);if(!t)continue;t.reserved=w.id;w.target=t.id;w.state='toTree'}else if(w.state==='toTree'){let t=s.trees.find(t=>t.id===w.target&&t.alive);if(!t){w.state='seek';w.target=null;continue}if(walkDirect(w,t.x,t.y,dt)){w.state='chop';w.chop=0}}else if(w.state==='chop'){w.chop+=dt;if(w.chop>=2.2){let t=s.trees.find(t=>t.id===w.target);if(t){t.alive=false;t.reserved=null}w.carry=true;w.state='return'}}else if(w.state==='return'){if(walkDirect(w,o.x,o.y,dt)){w.carry=false;w.state='seek';w.target=null;spawn('logs',o)}}}}
function sim(dt){for(let b of s.b){let d=T[b.type];if(!d.mk||b.type==='wood')continue;b.t+=dt;if(b.t<d.cy)continue;b.t=0;if(b.type==='mill'){if(!b.input.logs)continue;b.input.logs--;spawn('planks',b)}else spawn(d.mk,b)}updateWorkers(dt);updateCarriers(dt)}
function flagQueueText(f){let goods=s.goods.filter(v=>v.currentFlag===f.id&&!v.carrier);if(!goods.length)return 'Flag queue: empty';let counts={};for(let q of goods)counts[q.kind]=(counts[q.kind]||0)+1;return 'Flag queue: '+Object.entries(counts).map(([k,v])=>v+' '+k).join(' · ')}
function ui(){let q=[['wood','🪵'],['logs','🌲'],['planks','🟫'],['stone','🪨'],['food','🌾']];document.getElementById('res').innerHTML=q.map(([k,i])=>`<span class=r>${i} ${s.inv[k]|0}</span>`).join('')+`<span class=r>🚩 ${s.b.filter(b=>b.type==='flag').length}</span>`;let idle=s.carriers.filter(v=>v.state==='idle').length,blocked=s.goods.filter(v=>v.blocked).length,orphan=s.b.filter(b=>!['road','flag'].includes(b.type)&&!flagFor(b)).length,wc=s.workers.filter(w=>w.state==='chop').length;let extra='';if(selectedFlag){let f=s.b.find(b=>b.id===selectedFlag);if(f)extra=`<br><br><b>Selected Flag</b><br>${flagQueueText(f)}`}document.getElementById('status').innerHTML=`<br>Carriers: ${idle} idle · ${s.carriers.length-idle} busy<br>Goods waiting: ${s.goods.length}<br>Blocked goods: <b>${blocked}</b><br>Buildings missing flag: <b>${orphan}</b><br>Woodcutters chopping: <b>${wc}</b><br>Completed: ${s.delivered}${extra}`}
let tb=document.getElementById('tools');Object.entries(T).forEach(([k,v])=>{let b=document.createElement('button');b.innerHTML=v.i+'<br>'+v.n;b.onclick=()=>{sel=k;[...tb.children].forEach(z=>z.classList.toggle('on',z===b))};if(k===sel)b.classList.add('on');tb.appendChild(b)});
function drawTree(t){if(!t.alive)return;let p=iso(t.x,t.y),z=cam.z;g.fillStyle='#5a3d24';g.fillRect(p.x-1.4*z,p.y+12*z,2.8*z,8*z);g.fillStyle='#245e32';g.beginPath();g.arc(p.x,p.y+8*z,7*z,0,7);g.fill();g.fillStyle='#33723c';g.beginPath();g.arc(p.x-3*z,p.y+6*z,5*z,0,7);g.fill()}
function drawBuilding(b){let p=iso(b.x,b.y),z=cam.z,d=T[b.type];if(b.type==='road'){diamond(b.x,b.y,'#987d54','#65533b');return}if(b.type==='flag'){let ok=connectedFlag(b),selF=selectedFlag===b.id;diamond(b.x,b.y,selF?'#c5a65f':ok?'#9a845b':'#7a5146',selF?'#ffe58a':'#65533b');g.strokeStyle='#51341f';g.lineWidth=2*z;g.beginPath();g.moveTo(p.x,p.y+20*z);g.lineTo(p.x,p.y-8*z);g.stroke();g.fillStyle=ok?'#d34135':'#f0a33a';g.beginPath();g.moveTo(p.x,p.y-8*z);g.lineTo(p.x+13*z,p.y-3*z);g.lineTo(p.x,p.y+2*z);g.fill();return}g.save();g.translate(p.x,p.y+15*z);g.fillStyle='#0004';g.beginPath();g.ellipse(0,8*z,21*z,7*z,0,0,7);g.fill();if(b.type==='farm'){g.fillStyle='#c3a44b';g.fillRect(-24*z,-3*z,48*z,16*z)}else if(b.type==='tower'){g.fillStyle='#777';g.fillRect(-13*z,-30*z,26*z,42*z)}else{g.fillStyle=b.type==='quarry'?'#77736d':b.type==='store'?'#74563a':'#9a6540';g.fillRect(-18*z,-13*z,36*z,25*z);g.fillStyle='#493526';g.beginPath();g.moveTo(-23*z,-13*z);g.lineTo(0,-29*z);g.lineTo(23*z,-13*z);g.fill();g.fillStyle='#e1c98b';g.fillRect(-4*z,-1*z,8*z,13*z)}g.restore();let f=flagFor(b);g.fillStyle=f?'#6bd36b':'#f2b64f';g.beginPath();g.arc(p.x+18*z,p.y-7*z,3.5*z,0,7);g.fill();if(z>.65){g.fillStyle='#182016';g.font=`${10*z}px system-ui`;g.textAlign='center';g.fillText(d.n+(b.type==='mill'&&b.input.logs?' ['+b.input.logs+']':''),p.x,p.y+38*z)}}
function drawGoods(){for(let v of s.goods){let p=iso(v.x,v.y),z=cam.z;g.fillStyle=v.blocked?'#f04444':v.kind==='logs'?'#6f4b2b':v.kind==='planks'?'#b27a46':v.kind==='stone'?'#d2d0c8':'#e2bf47';g.fillRect(p.x-5*z,p.y+10*z,10*z,8*z);if(v.blocked){g.strokeStyle='#fff';g.strokeRect(p.x-6*z,p.y+9*z,12*z,10*z)}}}
function drawPeople(){for(let v of s.carriers){let p=iso(v.x,v.y),z=cam.z;g.fillStyle='#f3d8ad';g.beginPath();g.arc(p.x,p.y+8*z,3*z,0,7);g.fill();g.fillStyle=v.carry?'#c98c3e':'#7b3f36';g.fillRect(p.x-3*z,p.y+11*z,6*z,9*z)}for(let w of s.workers){let p=iso(w.x,w.y),z=cam.z;g.fillStyle='#f3d8ad';g.beginPath();g.arc(p.x,p.y+7*z,3*z,0,7);g.fill();g.fillStyle=w.state==='chop'?'#b55a36':'#365b86';g.fillRect(p.x-3*z,p.y+10*z,6*z,9*z);if(w.carry){g.fillStyle='#6f4b2b';g.fillRect(p.x+3*z,p.y+9*z,7*z,4*z)}if(w.state==='chop'){g.strokeStyle='#ddd';g.lineWidth=1.3*z;g.beginPath();g.moveTo(p.x+3*z,p.y+11*z);g.lineTo(p.x+8*z,p.y+5*z);g.stroke()}}}
function render(){g.setTransform(D,0,0,D,0,0);g.fillStyle='#5e8d4d';g.fillRect(0,0,innerWidth,innerHeight);for(let sum=0;sum<W+H;sum++)for(let a=0;a<W;a++){let b=sum-a;if(b<0||b>=H)continue;diamond(a,b,(a+b)%2?'#79a85c':'#82ae62','#456f40')}for(let t of s.trees)drawTree(t);[...s.b].sort((a,b)=>a.x+a.y-b.x-b.y).forEach(drawBuilding);drawGoods();drawPeople()}
function demo(){for(let a=10;a<22;a++)add('road',a,16,1);for(let b=12;b<21;b++)add('road',16,b,1);[['flag',13,16],['flag',16,16],['flag',20,16],['flag',16,18],['wood',13,15],['mill',15,15],['quarry',17,15],['farm',20,17],['house',14,17],['store',17,18],['tower',20,15]].forEach(v=>add(...v,1));initTrees();ensureCarriers();let p=iso(16,16);cam.x+=innerWidth*.5-p.x;cam.y+=innerHeight*.48-p.y;ui()}
c.addEventListener('pointerdown',e=>{drag=1;moved=0;last={x:e.clientX,y:e.clientY};c.setPointerCapture(e.pointerId)});c.addEventListener('pointermove',e=>{if(!drag)return;let dx=e.clientX-last.x,dy=e.clientY-last.y;if(Math.hypot(dx,dy)>3)moved=1;cam.x+=dx;cam.y+=dy;last={x:e.clientX,y:e.clientY}});c.addEventListener('pointerup',e=>{if(!moved){let p=uniso(e.clientX,e.clientY),o=at(p.x,p.y);if(o&&o.type==='flag'){selectedFlag=o.id;ui();toast(flagQueueText(o))}else add(sel,p.x,p.y)}drag=0});c.addEventListener('wheel',e=>{e.preventDefault();cam.z=Math.max(.45,Math.min(1.7,cam.z*Math.exp(-e.deltaY*.001)))},{passive:false});
demo();function loop(t){let dt=Math.min(.05,(t-t0)/1000);t0=t;sim(dt);render();if((t|0)%30===0)ui();requestAnimationFrame(loop)}requestAnimationFrame(loop)
})();