import{nextId}from'./state.js';import{adjacentFlag}from'./world.js';
export function segmentKey(a,b){return a.id<b.id?`${a.id}-${b.id}`:`${b.id}-${a.id}`}
export function goodsAtFlag(state,flagId){return state.goods.filter(g=>g.currentFlag===flagId&&!g.carrierId)}
export function cargoSummary(state,flagId){const counts={};for(const good of goodsAtFlag(state,flagId))counts[good.kind]=(counts[good.kind]||0)+1;return counts}
export function connectedSegments(state,flagId){return state.segments.filter(s=>s.a===flagId||s.b===flagId)}
export function enqueueGood(state,good){state.goods.push(good);return good}
function flagGraph(state,start,goal){const q=[start.id],prev=new Map(),seen=new Set(q);for(let h=0;h<q.length;h++){const id=q[h];if(id===goal.id){const out=[];let n=id;while(n!=null){out.push(n);n=prev.get(n)}return out.reverse()}for(const s of connectedSegments(state,id)){const n=s.a===id?s.b:s.a;if(!seen.has(n)){seen.add(n);prev.set(n,id);q.push(n)}}}return[]}
function stock(b,kind){return(b.input?.[kind]||0)+(b.output?.[kind]||0)}
function inbound(state,b,kind){return state.goods.filter(g=>g.destinationId===b.id&&g.kind===kind).length}
function demand(state,b,kind){if(b.type==='mill'&&kind==='logs')return Math.max(0,6-stock(b,'logs')-inbound(state,b,'logs'));if(b.type==='store')return 999;return 0}
export function destinationFor(state,kind,source){let best=null;for(const b of state.buildings){const f=adjacentFlag(state,b);if(!f)continue;const need=demand(state,b,kind);if(need<=0)continue;const route=flagGraph(state,source,f);if(route.length&&(!best||((b.type==='mill'&&kind==='logs')&&!best.priority)||((b.type==='mill'&&kind==='logs')===best.priority&&route.length<best.route.length)))best={building:b,flag:f,route,priority:b.type==='mill'&&kind==='logs'}}return best}
export function spawnCargo(state,kind,producer){const source=adjacentFlag(state,producer);if(!source)return null;producer.output=producer.output||{};producer.output[kind]=(producer.output[kind]||0)+1;const dest=destinationFor(state,kind,source);if(!dest)return null;producer.output[kind]--;const good={id:nextId(state,'good'),kind,producerId:producer.id,destinationId:dest.building.id,currentFlag:source.id,route:dest.route,routeIndex:0,carrierId:null,rest:0};state.goods.push(good);return good}
export function receiveCargo(state,good){const b=state.buildings.find(v=>v.id===good.destinationId);if(!b)return;b.input=b.input||{};b.output=b.output||{};if(b.type==='mill'&&good.kind==='logs')b.input.logs=(b.input.logs||0)+1;else if(b.type==='store'){b.input[good.kind]=(b.input[good.kind]||0)+1;state.inventory[good.kind]=(state.inventory[good.kind]||0)+1}else b.input[good.kind]=(b.input[good.kind]||0)+1;state.stats.delivered++;state.goods=state.goods.filter(v=>v.id!==good.id)}
export function dispatchStoredOutputs(state){for(const b of state.buildings){if(!b.output)continue;for(const[kind,count]of Object.entries(b.output)){if(count<=0)continue;const source=adjacentFlag(state,b);if(!source)continue;const dest=destinationFor(state,kind,source);if(!dest)continue;b.output[kind]--;state.goods.push({id:nextId(state,'good'),kind,producerId:b.id,destinationId:dest.building.id,currentFlag:source.id,route:dest.route,routeIndex:0,carrierId:null,rest:0})}}}
