import './main-v28.js';
import{nextId}from'./state.js';
import{adjacentFlag}from'./world.js';
const state=window.settlers.state;
const TYPES=['coal','iron','gold','stone'];const ICON={coal:'⚫',iron:'🔩',gold:'🟡',stone:'🪨'};
state.deposits=[];state.geology={surveyed:0,active:false};state.mining={coal:0,iron:0,gold:0,stone:0};state.mineralTransit=[];state.mineralDelivered={coal:0,iron:0,gold:0,stone:0};
for(let i=0;i<18;i++)state.deposits.push({id:i+1,x:3+(i*11)%27,y:3+(i*7)%21,type:TYPES[i%4],amount:12+(i*9)%28,surveyed:false});
function route(start,goal){const q=[start.id],prev=new Map(),seen=new Set(q);for(let h=0;h<q.length;h++){const id=q[h];if(id===goal.id){const out=[];let n=id;while(n!=null){out.push(n);n=prev.get(n)}return out.reverse()}for(const s of state.segments){if(s.a!==id&&s.b!==id)continue;const n=s.a===id?s.b:s.a;if(!seen.has(n)){seen.add(n);prev.set(n,id);q.push(n)}}}return[]}
function survey(){if(state.geology.active)return;state.geology.active=true;const e=document.querySelector('#buildMsg');if(e)e.textContent='🧭 Geologist is surveying rocky terrain…';let step=0;const timer=setInterval(()=>{const hidden=state.deposits.filter(d=>!d.surveyed);if(!hidden.length||step++>=4){clearInterval(timer);state.geology.active=false;return}const d=hidden[Math.floor((hidden.length-1)*((step*37)%100)/100)];d.surveyed=true;state.geology.surveyed++;const m=document.querySelector('#buildMsg');if(m)m.textContent=`🧭 Survey marker found: ${ICON[d.type]} ${d.type.toUpperCase()} deposit (${d.amount} units).`},900)}
function mine(type){const d=state.deposits.find(x=>x.surveyed&&x.type===type&&x.amount>0);if(!d){const e=document.querySelector('#buildMsg');if(e)e.textContent=`❌ No surveyed ${type} deposit available. Send the Geologist first.`;return}const store=state.buildings.find(b=>b.type==='store'),sf=store&&adjacentFlag(state,store);if(!store||!sf){const e=document.querySelector('#buildMsg');if(e)e.textContent='❌ Storage must be connected to the flag network before minerals can move.';return}const source=state.flags.reduce((best,f)=>!best||Math.hypot(f.x-d.x,f.y-d.y)<Math.hypot(best.x-d.x,best.y-d.y)?f:best,null);if(!source){const e=document.querySelector('#buildMsg');if(e)e.textContent='❌ No flag exists to receive mined cargo.';return}const r=route(source,sf);if(!r.length){const e=document.querySelector('#buildMsg');if(e)e.textContent='❌ Deposit has no connected flag route to Storage.';return}d.amount--;state.mining[type]++;const good={id:nextId(state,'good'),kind:type,producerId:null,destinationId:store.id,currentFlag:source.id,route:r,routeIndex:0,carrierId:null,rest:0,mineralDelivery:true,mineralKind:type};state.goods.push(good);state.mineralTransit.push(good.id);const e=document.querySelector('#buildMsg');if(e)e.textContent=`⛏️ Extracted 1 ${type}. It is now physical cargo at Flag #${source.id} and must travel to Storage.`}
function settleMinerals(){const store=state.buildings.find(b=>b.type==='store'),sf=store&&adjacentFlag(state,store);if(sf)for(const id of [...state.mineralTransit]){const g=state.goods.find(x=>x.id===id);if(!g){state.mineralTransit=state.mineralTransit.filter(x=>x!==id);continue}if(g.currentFlag===sf.id&&!g.carrierId){state.goods=state.goods.filter(x=>x.id!==g.id);state.mineralTransit=state.mineralTransit.filter(x=>x!==g.id);store.output[g.mineralKind]=(store.output[g.mineralKind]||0)+1;state.inventory[g.mineralKind]=(state.inventory[g.mineralKind]||0)+1;state.mineralDelivered[g.mineralKind]++;const e=document.querySelector('#buildMsg');if(e)e.textContent=`🏠 ${ICON[g.mineralKind]} ${g.mineralKind} physically reached Storage.`}}requestAnimationFrame(settleMinerals)}requestAnimationFrame(settleMinerals);
const panel=document.querySelector('.panel');panel.insertAdjacentHTML('beforeend',`<hr><div><b>🧭 Geological Survey & Mining · v29.1</b><br><small>Minerals begin hidden. Survey first; mined output is physical cargo.</small><div style="display:flex;gap:6px;overflow-x:auto;padding:7px 0"><button data-survey="1">🧭 Send Geologist</button><button data-mine="coal">⚫ Mine Coal</button><button data-mine="iron">🔩 Mine Iron</button><button data-mine="gold">🟡 Mine Gold</button><button data-mine="stone">🪨 Mine Stone</button></div><div id="v29geo"></div></div>`);
panel.addEventListener('pointerup',e=>{const s=e.target.closest('[data-survey]');if(s){e.preventDefault();e.stopPropagation();survey();return}const b=e.target.closest('[data-mine]');if(b){e.preventDefault();e.stopPropagation();mine(b.dataset.mine)}});
function render(){const e=document.querySelector('#v29geo');if(e){const found=state.deposits.filter(d=>d.surveyed);e.innerHTML=`Surveyed deposits: <b>${found.length}/${state.deposits.length}</b>${state.geology.active?' · 🧭 surveying':''}<br>`+(found.length?found.map(d=>`${ICON[d.type]} ${d.type}:${d.amount}`).join(' · '):'No mineral markers discovered yet.')+`<br>⛏️ Extracted: ${TYPES.map(t=>`${t} ${state.mining[t]}`).join(' · ')}<br>📦 In transit: <b>${state.mineralTransit.length}</b><br>🏠 Stored deliveries: ${TYPES.map(t=>`${t} ${state.mineralDelivered[t]}`).join(' · ')}`}requestAnimationFrame(render)}requestAnimationFrame(render);
