import './main-v28.js';
const state=window.settlers.state;
const TYPES=['coal','iron','gold','stone'];const ICON={coal:'⚫',iron:'🔩',gold:'🟡',stone:'🪨'};
state.deposits=[];state.geology={surveyed:0,active:false};state.mining={coal:0,iron:0,gold:0,stone:0};
// Deterministic hidden deposits concentrated around rocky terrain.
for(let i=0;i<18;i++)state.deposits.push({id:i+1,x:3+(i*11)%27,y:3+(i*7)%21,type:TYPES[i%4],amount:12+(i*9)%28,surveyed:false});
function survey(){if(state.geology.active)return;state.geology.active=true;const e=document.querySelector('#buildMsg');if(e)e.textContent='🧭 Geologist is surveying rocky terrain…';let step=0;const timer=setInterval(()=>{const hidden=state.deposits.filter(d=>!d.surveyed);if(!hidden.length||step++>=4){clearInterval(timer);state.geology.active=false;return}const d=hidden[Math.floor((hidden.length-1)*((step*37)%100)/100)];d.surveyed=true;state.geology.surveyed++;const m=document.querySelector('#buildMsg');if(m)m.textContent=`🧭 Survey marker found: ${ICON[d.type]} ${d.type.toUpperCase()} deposit (${d.amount} units).`},900)}
function mine(type){const d=state.deposits.find(x=>x.surveyed&&x.type===type&&x.amount>0);if(!d){const e=document.querySelector('#buildMsg');if(e)e.textContent=`❌ No surveyed ${type} deposit available. Send the Geologist first.`;return}d.amount--;state.mining[type]++;const store=state.buildings.find(b=>b.type==='store');if(store){store.output[type]=(store.output[type]||0)+1;state.inventory[type]=(state.inventory[type]||0)+1}const e=document.querySelector('#buildMsg');if(e)e.textContent=`⛏️ Extracted 1 ${type}. Deposit has ${d.amount} remaining. Output entered Storage.`}
const panel=document.querySelector('.panel');panel.insertAdjacentHTML('beforeend',`<hr><div><b>🧭 Geological Survey & Mining · v29</b><br><small>Minerals begin hidden. Survey first; extraction is finite.</small><div style="display:flex;gap:6px;overflow-x:auto;padding:7px 0"><button data-survey="1">🧭 Send Geologist</button><button data-mine="coal">⚫ Mine Coal</button><button data-mine="iron">🔩 Mine Iron</button><button data-mine="gold">🟡 Mine Gold</button><button data-mine="stone">🪨 Mine Stone</button></div><div id="v29geo"></div></div>`);
panel.addEventListener('pointerup',e=>{const s=e.target.closest('[data-survey]');if(s){e.preventDefault();e.stopPropagation();survey();return}const b=e.target.closest('[data-mine]');if(b){e.preventDefault();e.stopPropagation();mine(b.dataset.mine)}});
function render(){const e=document.querySelector('#v29geo');if(e){const found=state.deposits.filter(d=>d.surveyed);e.innerHTML=`Surveyed deposits: <b>${found.length}/${state.deposits.length}</b>${state.geology.active?' · 🧭 surveying':''}<br>`+(found.length?found.map(d=>`${ICON[d.type]} ${d.type}:${d.amount}`).join(' · '):'No mineral markers discovered yet.')+`<br>Extracted: ${TYPES.map(t=>`${t} ${state.mining[t]}`).join(' · ')}`}requestAnimationFrame(render)}requestAnimationFrame(render);
