import{walkDirect}from'./workers.js';
import{adjacentFlag}from'./world.js';
function nearestResource(list,o,max=8){const a=list.filter(v=>v.alive&&!v.reserved);a.sort((p,q)=>(Math.abs(p.x-o.x)+Math.abs(p.y-o.y))-(Math.abs(q.x-o.x)+Math.abs(q.y-o.y)));return a.find(v=>Math.abs(v.x-o.x)+Math.abs(v.y-o.y)<=max)||null}
export function updateWoodcutter(state,w,o,dt,spawnGood){if(w.state==='seek'){const t=nearestResource(state.trees,o,8);if(!t)return;t.reserved=w.id;w.targetId=t.id;w.state='to-site'}else if(w.state==='to-site'){const t=state.trees.find(v=>v.id===w.targetId&&v.alive);if(!t){w.state='seek';w.targetId=null;return}if(walkDirect(w,t.x,t.y,dt)){w.state='work';w.timer=0}}else if(w.state==='work'){w.timer+=dt;if(w.timer>=2.2){const t=state.trees.find(v=>v.id===w.targetId);if(t){t.alive=false;t.reserved=null}w.carry='logs';w.state='return'}}else if(w.state==='return'&&walkDirect(w,o.x,o.y,dt)){w.carry=null;w.targetId=null;spawnGood('logs',o);w.state='seek'}}
export function updateStonecutter(state,w,o,dt,spawnGood){if(w.state==='seek'){const r=nearestResource(state.rocks,o,9);if(!r)return;r.reserved=w.id;w.targetId=r.id;w.state='to-site'}else if(w.state==='to-site'){const r=state.rocks.find(v=>v.id===w.targetId&&v.alive);if(!r){w.state='seek';w.targetId=null;return}if(walkDirect(w,r.x,r.y,dt)){w.state='work';w.timer=0}}else if(w.state==='work'){w.timer+=dt;if(w.timer>=2.8){const r=state.rocks.find(v=>v.id===w.targetId);if(r){r.alive=false;r.reserved=null}w.carry='stone';w.state='return'}}else if(w.state==='return'&&walkDirect(w,o.x,o.y,dt)){w.carry=null;w.targetId=null;spawnGood('stone',o);w.state='seek'}}
function farmSpot(state,o,w){const offsets=[[2,0],[2,1],[1,2],[0,2],[-1,2],[-2,1],[-2,0],[-1,-2],[1,-2]];for(let i=0;i<offsets.length;i++){const[dx,dy]=offsets[i],id=`c${o.id}-${i}`;if(!state.crops.some(c=>c.id===id))state.crops.push({id,x:o.x+dx,y:o.y+dy,alive:true,reserved:null,ownerId:o.id})}return state.crops.find(c=>c.ownerId===o.id&&c.alive&&!c.reserved)||null}
export function updateFarmer(state,w,o,dt,spawnGood){if(w.state==='seek'){const crop=farmSpot(state,o,w);if(!crop)return;crop.reserved=w.id;w.targetId=crop.id;w.state='to-site'}else if(w.state==='to-site'){const crop=state.crops.find(v=>v.id===w.targetId);if(!crop){w.state='seek';return}if(walkDirect(w,crop.x,crop.y,dt)){w.state='work';w.timer=0}}else if(w.state==='work'){w.timer+=dt;if(w.timer>=2.5){const crop=state.crops.find(v=>v.id===w.targetId);if(crop){crop.alive=false;crop.reserved=null;crop.regrowAt=performance.now()+7000}w.carry='food';w.state='return'}}else if(w.state==='return'&&walkDirect(w,o.x,o.y,dt)){w.carry=null;w.targetId=null;spawnGood('food',o);w.state='seek'}}
export function updateSawyer(state,w,o,dt,spawnGood){if(w.state==='wait-input'){w.x=o.x+.08;w.y=o.y+.08;if((o.input?.logs||0)>0){o.input.logs--;w.state='work';w.timer=0}}else if(w.state==='work'){w.timer+=dt;if(w.timer>=3.2){w.carry='planks';w.state='to-flag'}}else if(w.state==='to-flag'){const f=adjacentFlag(state,o);if(!f){w.state='wait-input';w.carry=null;return}if(walkDirect(w,f.x,f.y,dt)){w.carry=null;spawnGood('planks',o);w.state='return'}}else if(w.state==='return'&&walkDirect(w,o.x,o.y,dt)){w.state='wait-input'}}
export function updateProfessions(state,dt,spawnGood){const now=performance.now();for(const c of state.crops)if(!c.alive&&c.regrowAt&&now>=c.regrowAt){c.alive=true;c.regrowAt=0}for(const w of state.workers){const o=state.buildings.find(b=>b.id===w.ownerId);if(!o)continue;if(w.job==='wood')updateWoodcutter(state,w,o,dt,spawnGood);else if(w.job==='quarry')updateStonecutter(state,w,o,dt,spawnGood);else if(w.job==='farm')updateFarmer(state,w,o,dt,spawnGood);else if(w.job==='mill')updateSawyer(state,w,o,dt,spawnGood)}}
